In [2]:
import pandas as pd
import numpy as np

df_ds = pd.read_csv('titanic.csv')
df=df_ds.copy()
df = df.drop(df.columns[[10]],axis = 1)
df = df.dropna(axis=0)

_ft = input("Enter the Selected Feature Name: ")
_type = input("Enter the Feature Type: ")

loc=df.columns.get_loc(_ft)

X = df.iloc[:,[2,9]].values
y = df.iloc[:,loc].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


if _type=='Nominal':
    import iMICE
    
    def processAge(x):
        if x >= 0 and x < 2:
            return 0
        elif x >= 2 and x <= 12:
            return 1
        elif x >= 13 and x <= 59:
            return 2
        elif x >= 60:
            return 3
    
    df_ds['AgeCode'] = df_ds['Age'].map(processAge)
    
    df_2 = df_ds[['AgeCode', 'Pclass', 'Fare']].copy()
    
    mice_result = iMICE.iMICE(verbose=False, init_fill_method="median", impute_type="pmm", n_imputations=7).complete(np.matrix(df_2))
    
    df_3 = pd.DataFrame(mice_result, columns = ['AgeCode', 'Pclass', 'Fare'])
    df_ds['NewAge'] = df_3['AgeCode'].copy()
    

#Binary
elif _type=='Binary':
    import iMICE
    
    df_ds['AgeBinary'] = df['Age'].apply(lambda x: 1 if x >= 19 else 0)
    df_2 = df_ds[['AgeBinary', 'Pclass', 'Fare']].copy()
    
    mice_result = iMICE.iMICE(verbose=False, init_fill_method="median", impute_type="pmm", n_imputations=7).complete(np.matrix(df_2))
    
    df_3 = pd.DataFrame(mice_result, columns = ['AgeBinary', 'Pclass', 'Fare'])
    df_ds['NewAge'] = df_3['AgeBinary'].copy()
    

#Numeric
else:
    from sklearn.ensemble import RandomForestRegressor

    regressor = RandomForestRegressor(n_estimators=20, random_state=0)  
    regressor.fit(X_train, y_train)
    
    X_test_1=df_ds.iloc[:,[2,9]].values.copy()
    
    y_pred = regressor.predict(X_test_1)
    
    df_ds['RealAge'] = df_ds['Age'].copy()
    mf=df_ds['Age'].isnull()
    df_ds['New']=df_ds['Age'].copy()
    #df_ds['New']=df_ds['Age'].copy()
    df_ds['newAge'] = y_pred
    m=df_ds['New'].copy()
    m[mf]=df_ds['newAge']
    df_ds['New']=m
    df_ds = df_ds.drop(df_ds.columns[[14]],axis = 1)
    
    #output
    print('Prcessed Dataset is: ')
    

#Name Value
salutation = ["a v m", "admiraal", "air cdre", "air commodore", "air marshal", "air vice marshal", "alderman", "alhaji", "ambassador", "baron", "barones", "brig", "brig gen", "brig general", "brigadier", "brigadier general", "brother", "canon", "capt", "captain", "cardinal", "cdr", "chief", "cik", "cmdr", "col", "col dr", "colonel", "commandant", "commander", "commissioner", "commodore", "comte", "comtessa", "congressman", "conseiller", "consul", "conte", "contessa", "corporal", "councillor", "count", "countess", "crown prince", "crown princess", "dame", "datin", "dato", "datuk", "datuk seri",
            "deacon", "deaconess", "dean", "dhr", "dipl ing", "doctor", "dott", "dott sa", "dr", "dr ing", "dra", "drs", "embajador", "embajadora", "en", "encik", "eng", "eur ing", "exma sra", "exmo sr", "f o", "father", "first lieutient", "first officer", "flt lieut", "flying officer", "fr", "frau", "fraulein", "fru", "gen", "generaal", "general", "governor", "graaf", "gravin", "group captain", "grp capt", "h e dr", "h h", "h m", "h r h", "hajah", "haji", "hajim", "her highness", "her majesty", "herr", "high chief", "his highness",
            "his holiness", "his majesty", "hon", "hr", "hra", "ing", "ir", "jonkheer", "judge", "justice", "khun ying", "kolonel", "lady", "lcda", "lic", "lieut", "lieut cdr", "lieut col", "lieut gen", "lord", "m", "m l", "m r", "madame", "mademoiselle", "maj gen", "major", "master", "mevrouw", "miss", "mlle", "mme", "monsieur", "monsignor", "mr", "mrs", "ms", "mstr", "nti", "pastor", "president", "prince", "princess", "princesse", "prinses", "prof", "prof dr", "prof sir", "professor",
            "puan", "puan sri", "rabbi", "rear admiral", "rev", "rev canon", "rev dr", "rev mother", "reverend", "rva", "senator", "sergeant", "sheikh", "sheikha", "sig", "sig na", "sig ra", "sir", "sister", "sqn ldr", "sr", "sr d", "sra", "srta", "sultan", "tan sri", "tan sri dato", "tengku", "teuku",
            "mrs.", "mr.", "most.", "md.", "master.", "ms.", "alhaz", "hazi", "haji", "mohammad", "muhammad", "dr.", "miss", "prof.", "kazi", "engineer"] 
def processName(name):
        name = name.lower()  # Make name all letter in lowercase 
        namesplits = name.split()  # To break a large string down into smaller
        for sals in salutation:
            if sals in namesplits:
                namesplits.remove(sals) # To remove name salutation and save in namesplits variable
        
        trans = str.maketrans('', '', 'aeiou')  # The method maketrans() returns a translation table that maps each character in the intabstring into the character at the same position in the outtab string. outtab − This is the string having corresponding mapping character.
        for i, nams in enumerate(namesplits):  # enumerate() - It returns an enumerate object.
            namesplits[i] = nams[0] + nams[1:].translate(trans)  # translate() method takes the translation table to replace/translate characters in the given string as per the mapping table.
        
        name = ' '.join(namesplits)  # By join() - simply concatenate two strings
        
        name = name.replace('g', 'j')
        name = name.replace('z', 'j')
        name = name.replace('q', 'k')
        
        trans = str.maketrans('aeioubcdfhjklmnprstvwxy .-', 'tuvwxabcdefghijklmnopqrsyz')  # The string maketrans() method returns a mapping table for translation usable for translate() method.
        name = name.translate(trans)  # The string translate() method returns a string where each character is mapped to its corresponding character in the translation table.
        
        return name

df_ds['Name'] = df_ds['Name'].map(processName).copy()

df_ds

Enter the Selected Feature Name: Age
Enter the Feature Type: Binary

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeBinary,NewAge
0,1,0,3,"aljc,swpjsellm",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.0,1.0
1,2,1,1,"bijfm,sfejsalchrs(dhljbsalffmsnerl)",female,38.0,1,0,PC 17599,71.2833,C85,C,1.0,1.0
2,3,1,3,"eggjj,simmyshj",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.0,1.0
3,4,1,1,"dnlhh,sfbgmsenes(hhrsirskh)",female,35.0,1,0,113803,53.1000,C123,S,1.0,1.0
4,5,0,3,"thhj,sphhisejlr",male,35.0,0,0,373450,8.0500,NaN,S,1.0,1.0
5,6,0,3,"ilj,sfim",male,NaN,0,0,330877,8.4583,NaN,Q,NaN,1.0
6,7,0,1,"ibblner,sninersf",male,54.0,0,0,17463,51.8625,E46,S,1.0,1.0
7,8,0,3,"khmmj,sfmnshjlc",male,2.0,3,1,349909,21.0750,NaN,S,0.0,0.0
8,9,1,3,"fejmj,swmblsps(hmanesohehijsalf)",female,27.0,0,2,347742,11.1333,NaN,S,1.0,1.0
9,10,1,2,"jmml,sjbehms(chstbei)",female,14.0,1,0,237736,30.0708,NaN,C,0.0,0.0
10,11,1,3,"mjcmnli,simmysilflnsln",female,4.0,1,1,PP 9549,16.7000,G6,S,0.0,0.0
11,12,1,1,"ajjhh,simmysuhfane",female,58.0,0,0,113783,26.5500,C103,S,1.0,1.0
12,13,0,3,"mjclbbg,sphhisejlr",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,1.0,1.0
13,14,0,3,"tjclmmj,stjclmsfej",male,39.0,1,5,347082,31.2750,NaN,S,1.0,1.0
14,15,0,3,"omnli,simmysehcstijcstchdj",female,14.0,0,0,350406,7.8542,NaN,S,0.0,0.0
15,16,1,2,"ephnn,s(ilrscsgjfbi)",female,55.0,0,0,248706,16.0000,NaN,S,1.0,1.0
16,17,0,3,"lb,sufj",male,2.0,4,1,382652,29.1250,NaN,Q,0.0,0.0
17,18,1,2,"phhim,sbelhmsufj",male,NaN,0,0,244373,13.0000,NaN,S,NaN,1.0
18,19,0,3,"ojclskhjg,sfhms(ihsilsojcilnh)",female,31.0,1,0,345763,18.0000,NaN,S,1.0,1.0
19,20,1,3,"immhij,sdni",female,NaN,0,0,2649,7.2250,NaN,C,NaN,1.0
20,21,0,2,"drjjr,sfmkesf",male,35.0,0,0,239865,26.0000,NaN,S,1.0,1.0
21,22,1,2,"amhr,shpljb",male,34.0,0,0,248698,13.0000,D56,S,1.0,1.0
22,23,1,3,"ibfpj,simmystjjs""jj""",female,15.0,0,0,330923,8.0292,NaN,Q,0.0,0.0
23,24,1,1,"mhkl,sphhisneikmj",male,28.0,0,0,113788,35.5000,A6,S,1.0,1.0
24,25,0,3,"khmmj,simmysnlalfscjl",female,8.0,3,1,349909,21.0750,NaN,S,0.0,0.0
25,26,1,3,"tmkhjc,sblhswmbls(mhistfmnsuihsfejmmj)",female,38.0,1,5,347077,31.3875,NaN,S,1.0,1.0
26,27,0,3,"uil,sdllcsbeea",male,NaN,0,0,2631,7.2250,NaN,C,NaN,1.0
27,28,0,1,"dlnj,sbelhmsthqjcl",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,1.0,1.0
28,29,1,3,"w'cprl,simmysuhhjs""jhh""",female,NaN,0,0,330959,7.8792,NaN,Q,NaN,1.0
29,30,0,3,"ncldd,shh",male,NaN,0,0,349216,7.8958,NaN,S,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"fhm,sdlclbgsucplc",male,21.0,1,0,28134,11.5000,NaN,S,1.0,1.0
862,863,1,1,"mpdn,sdlclbgsfhs(ilflnsphhmsallj)",female,48.0,0,0,17466,25.9292,D17,S,1.0,1.0
863,864,0,3,"mf,simmysclnersucnes""chhr""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,NaN,1.0
864,865,0,2,"fhh,sfejsphhi",male,24.0,0,0,233866,13.0000,NaN,S,1.0,1.0
865,866,1,2,"armnli,s(glhj)",female,42.0,0,0,236852,13.0000,NaN,S,1.0,1.0
866,867,1,2,"cljsrsil,simmystmjbj",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C,1.0,1.0
867,868,0,1,"lahjf,spmejfnjstfmnmsv",male,31.0,0,0,PC 17590,50.4958,A24,S,1.0,1.0
868,869,0,3,"ojsihgag,skehij",male,NaN,0,0,345777,9.5000,NaN,S,NaN,1.0
869,870,1,3,"fejmj,selhcsnecl",male,4.0,1,1,347742,11.1333,NaN,S,0.0,0.0
870,871,0,3,"ahgb,sblj",male,26.0,0,0,349248,7.8958,NaN,S,1.0,1.0
871,872,1,1,"abgpne,slbelcshjlcs(mhhsijrkjr)",female,47.0,1,1,11751,52.5542,D35,S,1.0,1.0
872,873,0,1,"blhmmj,sdljmswhd",male,33.0,0,0,695,5.0000,B51 B53 B55,S,1.0,1.0
873,874,0,3,"ojclsblrmmj,sobnl",male,47.0,0,0,345765,9.0000,NaN,S,1.0,1.0
874,875,1,2,"tahmj,smihs(ejjespfmgr)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,1.0,1.0
875,876,1,3,"jfa,simmystchsgis""fj""",female,15.0,0,0,2667,7.2250,NaN,C,0.0,0.0
876,877,0,3,"fmndmmj,sthdlcswmmj",male,20.0,0,0,7534,9.8458,NaN,S,1.0,1.0
877,878,0,3,"knldd,sjch",male,19.0,0,0,349212,7.8958,NaN,S,1.0,1.0
878,879,0,3,"hhdd,sglmn",male,NaN,0,0,349217,7.8958,NaN,S,NaN,1.0
879,880,1,1,"knnl,sneimsfls(hhrsthqjsphmj)",female,56.0,0,1,11767,83.1583,C50,C,1.0,1.0
880,881,1,2,"mehhr,sphhis(ijnskllmesehh)",female,25.0,0,1,230433,26.0000,NaN,S,1.0,1.0
881,882,0,3,"ilgj,sfejj",male,33.0,0,0,349257,7.8958,NaN,S,1.0,1.0
882,883,0,3,"cehalf,simmysflcsxhlg",female,22.0,0,0,7552,10.5167,NaN,S,1.0,1.0
883,884,0,2,"ajdhc,sdlclbgsfim",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,1.0,1.0
884,885,0,3,"mnehh,sejlrsfl",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,1.0,1.0
885,886,0,3,"lb,sphhis(ilflnsjlnj)",female,39.0,0,5,382652,29.1250,NaN,Q,1.0,1.0
886,887,0,2,"ijnoh,sloysffm",male,27.0,0,0,211536,13.0000,NaN,S,1.0,1.0
887,888,1,1,"flei,simmysilflnsucne",female,19.0,0,0,112053,30.0000,B42,S,1.0,1.0
888,889,0,3,"fejmnj,simmysbneljsehjs""bll""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN,1.0
889,890,1,1,"ael,sglhsephh",male,26.0,0,0,111369,30.0000,C148,C,1.0,1.0
890,891,0,3,"chr,sknlbg",male,32.0,0,0,370376,7.7500,NaN,Q,1.0,1.0